frequency=50

[[PC]]
name='scada1'
ip='10.1.50.240'
code=true

[[PC]]
name='scada2'
ip='10.1.50.241'
code=true

[[PC]]
name='scada3'
ip='10.1.50.242'
code=true

[[PC]]
name='scada1'
ip='10.1.50.243'
code=true

[[Controller]]
name='A01'
ip='10.1.50.244'
netid='5.8.250.74.1.1'
plc="beckhoff"
template="template_1"
port=10320

[[Controller]]
name='A02'
ip='10.1.50.245'
netid=''
plc="phoenix"
template="template_2"

[[Controller]]
name='A03'
ip='10.1.50.246'
netid=''
plc="Bachmann"
template="template_3"
zftempale="template_4"
